services:
  quote-api:
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quote-api.rule=Host(`quote.nubcoder.com`)"
      - "traefik.http.routers.quote-api.entrypoints=websecure"
      - "traefik.http.routers.quote-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.quote-api.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 1G


networks:
  web:
    external: true
